### ISSUE TITLE
Arabic localized app, shows calender with persian numbers

### ISSUE THREAD

**Issue by MohamedEmish** [aminography/PrimeDatePicker#38]
set the calendar locale to be "ar", you will see the numbers of days shown are in Persian numbers, we need to show Arabic letters

**Comment by MohamedEmish** [comment]
```
private val ARABIC_DIGITS = charArrayOf(
        '0' + 1584,
        '1' + 1584,
        '2' + 1584,
        '3' + 1584,
        '4' + 1584,
        '5' + 1584,
        '6' + 1584,
        '7' + 1584,
        '8' + 1584,
        '9' + 1584
)
```
You can use these in your `languageUtils` file and check if the language name is "ar" or else 
that gonna fix it

**Comment by aminography** [comment]
Hi @MohamedEmish,
Thank you for reporting the issue, I will fix it soon.

**Comment by aminography** [comment]
Please update the version of `primecalendar` to `1.3.1`. The issue has been solved.

**Comment by MohamedEmish** [comment]
Hi Amin
I upgraded the library but the issue still there
I tried to contribute to the library but i couldn't push a branch with the
fix, so please fix it and keep me updated
thanks

**Comment by aminography** [comment]
Sorry for that.
Now it is fixed.
Update to:
```
dependencies {
    implementation 'com.aminography:primedatepicker:3.2.2'
    implementation 'com.aminography:primecalendar:1.3.2'
}
```

**Comment by MohamedEmish** [comment]
Fixed, Thank you
we can close it now
